import {
  BarChart3,
  BookOpenCheck,
  Boxes,
  Briefcase,
  Building2,
  Calculator,
  CalendarClock,
  CheckCircle,
  Circle,
  CircleSlash,
  ClipboardCheck,
  Compass,
  CreditCard,
  DatabaseBackup,
  Factory,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  Globe,
  Handshake,
  Headphones,
  Kanban,
  Layers,
  LayoutGrid,
  LifeBuoy,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MonitorPlay,
  Network,
  NotebookPen,
  Package,
  PackageCheck,
  PenLine,
  Plug,
  Presentation,
  ReceiptText,
  RefreshCw,
  ScanLine,
  Sheet,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Split,
  Store,
  Table,
  Target,
  Truck,
  User,
  Users,
  UsersRound,
  Video,
  Warehouse,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { cn } from '@/lib/utils';

/**
 * Katalog menyimpan nama ikon sebagai teks (kolom `icon`), bukan komponen.
 * Peta ini menerjemahkannya menjadi SVG inline sehingga halaman publik tidak
 * pernah memuat gambar dari internet dan tetap tajam di mode gelap.
 */
const ICONS: Record<string, LucideIcon> = {
  BarChart3,
  BookOpenCheck,
  Boxes,
  Briefcase,
  Building2,
  Calculator,
  CalendarClock,
  CheckCircle,
  Circle,
  CircleSlash,
  ClipboardCheck,
  Compass,
  CreditCard,
  DatabaseBackup,
  Factory,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  Globe,
  Handshake,
  Headphones,
  Kanban,
  Layers,
  LayoutGrid,
  LifeBuoy,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MonitorPlay,
  Network,
  NotebookPen,
  Package,
  PackageCheck,
  PenLine,
  Plug,
  Presentation,
  ReceiptText,
  RefreshCw,
  ScanLine,
  Sheet,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Split,
  Store,
  Table,
  Target,
  Truck,
  User,
  Users,
  UsersRound,
  Video,
  Warehouse,
  Wrench,
  Zap,
};

/**
 * Ikon katalog — selalu dekoratif.
 *
 * Nama fitur/kategori selalu tertulis di sebelahnya, jadi ikon disembunyikan
 * dari pembaca layar (WCAG 2.1 AA: gambar dekoratif tidak dibacakan).
 */
export function CatalogIcon({
  name,
  className,
}: {
  name: string | null | undefined;
  className?: string;
}) {
  const Icon = (name && ICONS[name]) || Package;
  return <Icon className={cn('size-5 shrink-0', className)} strokeWidth={1.75} aria-hidden="true" />;
}
